CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "description" varchar,
  "content" varchar,
  "author" int NOT NULL
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "text" varchar NOT NULL,
  "author" int NOT NULL
);

CREATE TABLE "post_comments" (
  "post_id" int NOT NULL,
  "comment_id" int NOT NULL
);

CREATE TABLE "post_tags" (
  "post_id" int NOT NULL,
  "tag_id" int NOT NULL
);

ALTER TABLE "posts" ADD FOREIGN KEY ("author") REFERENCES "users" ("id");

ALTER TABLE "post_comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_comments" ADD FOREIGN KEY ("comment_id") REFERENCES "comments" ("id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

insert into users (name, email, password, age) values
('John Doe', 'john.doe@domain.com', 'safe1234', '23'),
('Abisai Luna', 'abisai.luna@domain.com', '1234safe', '21');

insert into posts (title, description, content, author) values
('First post', 'Testing the posts', 2),
('OMG Second', 'This works!', 'randomImageURL', 1);

insert into tags (name) values
('Surprised'),
('Tired');

insert into comments (text, author) values
('Testing the comments', 1),
('Finally man. :)', 2);

insert into post_comments (post_id, comment_id) values
(1, 1),
(2, 2);

insert into post_tags (post_id, tag_id) values
(2, 1),
(1, 2);